words   db 'rural', 0
        db 'ufrpe', 0
        db 'sagaz', 0
        db 'negro', 0
        db 'termo', 0
        db 'mexer', 0
        db 'nobre', 0
        db 'senso', 0
        db 'afeto', 0
        db 'algoz', 0
        db 'plena', 0
        db 'fazer', 0
        db 'assim', 0
        db 'sutil', 0
        db 'vigor', 0
        db 'fosse', 0
        db 'sanar', 0
        db 'audaz', 0
        db 'poder', 0
        db 'ideia', 0
        db 'cerne', 0
        db 'inato', 0
        db 'moral', 0
        db 'desde', 0
        db 'sobre', 0
        db 'justo', 0
        db 'muito', 0
        db 'honra', 0
        db 'torpe', 0
        db 'sonho', 0
        db 'etnia', 0
        db 'anexo', 0
        db 'amigo', 0
        db 'tange', 0
        db 'lapso', 0
        db 'expor', 0
        db 'haver', 0
        db 'dengo', 0
        db 'tempo', 0
        db 'casal', 0
        db 'seara', 0
        db 'pesar', 0
        db 'ardil', 0
        db 'genro', 0
        db 'causa', 0
        db 'saber', 0
        db 'dizer', 0
        db 'posse', 0
        db 'coser', 0
        db 'dever', 0
        db 'tenaz', 0
        db 'prole', 0
        db 'corja', 0
        db 'brado', 0
        db 'crivo', 0
        db 'comum', 0
        db 'sendo', 0
        db 'temor', 0
        db 'ainda', 0
        db 'ceder', 0
        db 'digno', 0
        db 'pauta', 0
        db 'estar', 0
        db 'assaz', 0
        db 'culto', 0
        db 'atroz', 0
        db 'mundo', 0
        db 'censo', 0
        db 'fugaz', 0
        db 'gleba', 0
        db 'xibiu', 0
        db 'forte', 0
        db 'vulgo', 0
        db 'valha', 0
        db 'cozer', 0
        db 'denso', 0
        db 'pudor', 0
        db 'dogma', 0
        db 'regra', 0
        db 'criar', 0
        db 'louco', 0
        db 'jeito', 0
        db 'mesmo', 0
        db 'round', 0
        db 'ordem', 0
        db 'banal', 0
        db 'impor', 0
        db 'clava', 0
        db 'pedir', 0
        db 'homem', 0
        db 'feliz', 0
        db 'apraz', 0
        db 'tenro', 0
        db 'desse', 0
        db 'usura', 0
        db 'coisa', 0
        db 'servo', 0
        db 'todos', 0
        db 'prosa', 0
        db 'limbo', 0
        db 'forma', 0
        db 'presa', 0
        db 'viril', 0
        db 'ontem', 0
        db 'falar', 0
        db 'cunho', 0
        db 'manso', 0
        db 'devir', 0
        db 'meiga', 0
        db 'posso', 0
        db 'vendo', 0
        db 'certo', 0
        db 'fluir', 0
        db 'afago', 0
        db 'valor', 0
        db 'puder', 0
        db 'guisa', 0
        db 'visar', 0
        db 'acaso', 0
        db 'lugar', 0
        db 'temer', 0
        db 'falso', 0
        db 'abrir', 0
        db 'afins', 0
        db 'cisma', 0
        db 'pleno', 0
        db 'bruma', 0
        db 'legal', 0
        db 'obter', 0
        db 'gerar', 0
        db 'matiz', 0
        db 'crise', 0
        db 'praxe', 0
        db 'garbo', 0
        db 'burro', 0
        db 'senil', 0
        db 'fluxo', 0
        db 'havia', 0
        db 'enfim', 0
        db 'linda', 0
        db 'ritmo', 0
        db 'tomar', 0
        db 'olhar', 0
        db 'parvo', 0
        db 'morte', 0
        db 'brega', 0
        db 'levar', 0
        db 'bravo', 0
        db 'casta', 0
        db 'pulha', 0
        db 'favor', 0
        db 'vital', 0
        db 'prumo', 0
        db 'reter', 0
        db 'valia', 0
        db 'ajuda', 0
        db 'parco', 0
        db 'reles', 0
        db 'grato', 0
        db 'vivaz', 0
        db 'laico', 0
        db 'tecer', 0
        db 'possa', 0
        db 'falta', 0
        db 'ameno', 0
        db 'cabal', 0
        db 'ouvir', 0
        db 'prime', 0
        db 'carma', 0
        db 'viver', 0
        db 'nicho', 0
        db 'achar', 0
        db 'noite', 0
        db 'calma', 0
        db 'selar', 0
        db 'passo', 0
        db 'fator', 0
        db 'outro', 0
        db 'rogar', 0
        db 'anelo', 0
        db 'coeso', 0
        db 'farsa', 0
        db 'fardo', 0
        db 'pobre', 0
        db 'ativo', 0
        db 'citar', 0
        db 'sinto', 0
        db 'tendo', 0
        db 'rever', 0
        db 'adiar', 0
        db 'sonso', 0
        db 'leigo', 0
        db 'terra', 0
        db 'haste', 0
        db 'gente', 0
        db 'sesta', 0
        db 'humor', 0
        db 'cesta', 0
        db 'sulco', 0
        db 'deter', 0
        db 'tende', 0
        db 'revel', 0
        db 'exato', 0
        db 'velho', 0
        db 'amplo', 0
        db 'claro', 0
        db 'vemos', 0
        db 'atuar', 0
        db 'lavra', 0
        db 'labor', 0
        db 'imune', 0
        db 'feixe', 0
        db 'ponto', 0
        db 'igual', 0
        db 'ideal', 0
        db 'gesto', 0
        db 'marco', 0
        db 'hiato', 0
        db 'fonte', 0
        db 'terno', 0
        db 'ambos', 0
        db 'toada', 0
        db 'sonsa', 0
        db 'remir', 0
        db 'ficar', 0
        db 'capaz', 0
        db 'cauda', 0
        db 'jovem', 0
        db 'papel', 0
        db 'vazio', 0
        db 'inata', 0
        db 'tenra', 0
        db 'tanto', 0
        db 'velar', 0
        db 'relva', 0
        db 'xeque', 0
        db 'algum', 0
        db 'leito', 0
        db 'horda', 0
        db 'apoio', 0
        db 'probo', 0
        db 'doido', 0
        db 'raiva', 0
        db 'pouco', 0
        db 'nossa', 0
        db 'entre', 0
        db 'coesa', 0
        db 'sente', 0
        db 'vimos', 0
        db 'frase', 0
        db 'minha', 0
        db 'feito', 0
        db 'verso', 0
        db 'anuir', 0
        db 'botar', 0
        db 'rigor', 0
        db 'chuva', 0
        db 'cruel', 0
        db 'massa', 0
        db 'dorso', 0
        db 'brisa', 0
        db 'signo', 0
        db 'ciclo', 0
        db 'chata', 0
        db 'prece', 0
        db 'trama', 0
        db 'fauna', 0
        db 'credo', 0
        db 'lazer', 0
        db 'covil', 0
        db 'preso', 0
        db 'maior', 0
        db 'casto', 0
        db 'morar', 0
        db 'carro', 0
        db 'furor', 0
        db 'peste', 0
        db 'ambas', 0
        db 'pegar', 0
        db 'flora', 0
        db 'faina', 0
        db 'sorte', 0
        db 'seita', 0
        db 'adeus', 0
        db 'vetor', 0
        db 'houve', 0
        db 'livro', 0
        db 'setor', 0
        db 'senda', 0
        db 'liame', 0
        db 'meses', 0
        db 'manha', 0
        db 'pecha', 0
        db 'comer', 0
        db 'plano', 0
        db 'peixe', 0
        db 'beata', 0
        db 'aceso', 0
        db 'ardor', 0
        db 'nunca', 0
        db 'banzo', 0
        db 'visse', 0
        db 'vulto', 0
        db 'salvo', 0
        db 'ocaso', 0
        db 'breve', 0
        db 'vasto', 0
        db 'saiba', 0
        db 'antro', 0
        db 'morro', 0
        db 'birra', 0
        db 'pajem', 0
        db 'prado', 0
        db 'rezar', 0
        db 'reger', 0
        db 'mudar', 0
        db 'junto', 0
        db 'segue', 0
        db 'avaro', 0
        db 'motim', 0
        db 'sinal', 0
        db 'praia', 0
        db 'chulo', 0
        db 'parte', 0
        db 'campo', 0
        db 'lenda', 0
        db 'grupo', 0
        db 'acima', 0
        db 'andar', 0
        db 'fugir', 0
        db 'treta', 0
        db 'anais', 0
        db 'brava', 0
        db 'risco', 0
        db 'parar', 0
        db 'fruir', 0
        db 'leite', 0
        db 'fitar', 0
        db 'rapaz', 0
        db 'jazia', 0
        db 'agora', 0
        db 'prazo', 0
        db 'tenso', 0
        db 'gerir', 0
        db 'puxar', 0
        db 'alude', 0
        db 'antes', 0
        db 'bando', 0
        db 'norma', 0
        db 'tosco', 0
        db 'tirar', 0
        db 'malta', 0
        db 'psico', 0
        db 'exame', 0
        db 'texto', 0
        db 'conta', 0
        db 'reino', 0
        db 'verbo', 0
        db 'arcar', 0
        db 'praga', 0
        db 'corpo', 0
        db 'aonde', 0
        db 'filho', 0
        db 'venal', 0
        db 'cheio', 0
        db 'preto', 0
        db 'prova', 0
        db 'quase', 0
        db 'quota', 0
        db 'voraz', 0
        db 'traga', 0
        db 'certa', 0
        db 'logro', 0
        db 'fatal', 0
        db 'festa', 0
        db 'soldo', 0
        db 'acesa', 0
        db 'turba', 0
        db 'apego', 0
        db 'sumir', 0
        db 'fixar', 0
        db 'pompa', 0
        db 'fatos', 0
        db 'ligar', 0
        db 'coito', 0
        db 'caixa', 0
        db 'alado', 0
        db 'messe', 0
        db 'mente', 0
        db 'solto', 0
        db 'perda', 0
        db 'tocar', 0
        db 'magia', 0
        db 'lindo', 0
        db 'afora', 0
        db 'verve', 0
        db 'fraco', 0
        db 'dessa', 0
        db 'livre', 0
        db 'parca', 0
        db 'turva', 0
        db 'tinha', 0
        db 'apelo', 0
        db 'exijo', 0
        db 'grave', 0
        db 'jirau', 0
        db 'lidar', 0
        db 'opaco', 0
        db 'firme', 0
        db 'glosa', 0
        db 'sabia', 0
        db 'parva', 0
        db 'trupe', 0
        db 'longe', 0
        db 'pardo', 0
        db 'fenda', 0
        db 'elite', 0
        db 'nosso', 0
        db 'faixa', 0
        db 'astro', 0
        db 'bater', 0
        db 'vezes', 0
        db 'navio', 0
        db 'grata', 0
        db 'salve', 0
        db 'viria', 0
        db 'autor', 0
        db 'sexta', 0
        db 'supra', 0
        db 'ficha', 0
        db 'pique', 0
        db 'porta', 0
        db 'cioso', 0
        db 'reses', 0
        db 'atual', 0
        db 'deixa', 0
        db 'junco', 0
        db 'macio', 0
        db 'bicho', 0
        db 'calda', 0
        db 'douto', 0
        db 'besta', 0
        db 'verba', 0
        db 'cousa', 0
        db 'abuso', 0
        db 'abriu', 0
        db 'posto', 0
        db 'curso', 0
        db 'judeu', 0
        db 'molho', 0
        db 'locus', 0
        db 'caber', 0
        db 'supor', 0
        db 'torso', 0
        db 'drops', 0
        db 'light', 0
        db 'extra', 0
        db 'bioma', 0
        db 'desta', 0
        db 'culpa', 0
        db 'menos', 0
        db 'zelar', 0
        db 'vosso', 0
        db 'asilo', 0
        db 'combo', 0
        db 'vinha', 0
        db 'turvo', 0
        db 'baixo', 0
        db 'gosto', 0
        db 'pisar', 0
        db 'agudo', 0
        db 'advir', 0
        db 'suave', 0
        db 'rouca', 0
        db 'super', 0
        db 'ereto', 0
        db 'chato', 0
        db 'facho', 0
        db 'aluno', 0
        db 'estio', 0
        db 'turma', 0
        db 'paira', 0
        db 'finda', 0
        db 'facto', 0
        db 'pilar', 0
        db 'amena', 0
        db 'meigo', 0
        db 'surja', 0
        db 'chama', 0
        db 'peito', 0
        db 'mosto', 0
        db 'piada', 0
        db 'brabo', 0
        db 'feudo', 0
        db 'tento', 0
        db 'autos', 0
        db 'rumor', 0
        db 'urgia', 0
        db 'museu', 0
        db 'local', 0
        db 'cocho', 0
        db 'tetra', 0
        db 'mesma', 0
        db 'clean', 0
        db 'geral', 0
        db 'lasso', 0
        db 'optar', 0
        db 'boato', 0
        db 'drama', 0
        db 'hobby', 0
        db 'poema', 0
        db 'passa', 0
        db 'folga', 0
        db 'medir', 0
        db 'coral', 0
        db 'teste', 0
        db 'clima', 0
        db 'forem', 0
        db 'rubro', 0
        db 'pacto', 0
        db 'ateia', 0
        db 'poeta', 0
        db 'crime', 0
        db 'ponha', 0
        db 'golpe', 0
        db 'feroz', 0
        db 'busca', 0
        db 'cetro', 0
        db 'cacho', 0
        db 'tacha', 0
        db 'penta', 0
        db 'vigia', 0
        db 'aroma', 0
        db 'letal', 0
        db 'idoso', 0
        db 'daqui', 0
        db 'aviso', 0
        db 'verde', 0
        db 'calmo', 0
        db 'monte', 0
        db 'amiga', 0
        db 'hoste', 0
        db 'carta', 0
        db 'pasmo', 0
        db 'riste', 0
        db 'swing', 0
        db 'ecoar', 0
        db 'rival', 0
        db 'vetar', 0
        db 'plumo', 0
        db 'fazia', 0
        db 'briga', 0
        db 'tribo', 0
        db 'falha', 0
        db 'monge', 0
        db 'conto', 0
        db 'cover', 0
        db 'lesse', 0
        db 'pedra', 0
        db 'plebe', 0
        db 'roupa', 0
        db 'finjo', 0
        db 'escol', 0
        db 'tarde', 0
        db 'artur', 0
        db 'corso', 0
        db 'venha', 0
        db 'axila', 0
        db 'manga', 0
        db 'chefe', 0
        db 'grama', 0
        db 'fruto', 0
        db 'plaga', 0
        db 'macro', 0
        db 'casar', 0
        db 'civil', 0
        db 'cargo', 0
        db 'saldo', 0
        db 'sarau', 0
        db 'vento', 0
        db 'itens', 0
        db 'perco', 0
        db 'farta', 0
        db 'berro', 0
        db 'virar', 0
        db 'ornar', 0
        db 'arado', 0
        db 'nuvem', 0
        db 'viram', 0
        db 'troca', 0
        db 'pinho', 0
        db 'bruta', 0
        db 'catre', 0
        db 'beijo', 0
        db 'tiver', 0
        db 'magna', 0
        db 'fosso', 0
        db 'seixo', 0
        db 'jejum', 0
        db 'traje', 0
        db 'amada', 0
        db 'deste', 0
        db 'estro', 0
        db 'assar', 0
        db 'areia', 0
        db 'surto', 0
        db 'trato', 0
        db 'renda', 0
        db 'perto', 0
        db 'bruto', 0
        db 'tutor', 0
        db 'inter', 0
        db 'stand', 0
        db 'porte', 0
        db 'amado', 0
        db 'canso', 0
        db 'guria', 0
        db 'volta', 0
        db 'gabar', 0
        db 'feita', 0
        db 'bazar', 0
        db 'vedar', 0
        db 'silvo', 0
        db 'arfar', 0
        db 'natal', 0
        db 'depor', 0
        db 'grota', 0
        db 'irado', 0
        db 'nesse', 0
        db 'tchau', 0
        db 'jogar', 0
        db 'cifra', 0
        db 'bucho', 0
        db 'laudo', 0
        db 'pomar', 0
        db 'vadio', 0
        db 'close', 0
        db 'fossa', 0
        db 'pavor', 0
        db 'odiar', 0
        db 'clero', 0
        db 'rocha', 0
        db 'deram', 0
        db 'segar', 0
        db 'vagar', 0
        db 'minar', 0
        db 'bolsa', 0
        db 'aviar', 0
        db 'xucro', 0
        db 'negar', 0
        db 'canto', 0
        db 'meche', 0
        db 'visto', 0
        db 'todas', 0
        db 'molde', 0
        db 'cenho', 0
        db 'densa', 0
        db 'pasma', 0
        db 'cinto', 0
        db 'etapa', 0
        db 'nesta', 0
        db 'logos', 0
        db 'proto', 0
        db 'marca', 0
        db 'chula', 0
        db 'vista', 0
        db 'santo', 0
        db 'ferpa', 0
        db 'horto', 0
        db 'tenha', 0
        db 'troco', 0
        db 'largo', 0
        db 'nessa', 0
        db 'paiol', 0
        db 'morfo', 0
        db 'velha', 0
        db 'cheia', 0
        db 'varoa', 0
        db 'urdir', 0
        db 'penso', 0
        db 'cerca', 0
        db 'lesto', 0
        db 'pugna', 0
        db 'podar', 0
        db 'vasta', 0
        db 'burra', 0
        db 'coroa', 0
        db 'ileso', 0
        db 'salmo', 0
        db 'ufano', 0
        db 'mocho', 0
        db 'esgar', 0
        db 'fundo', 0
        db 'final', 0
        db 'frota', 0
        db 'letra', 0
        db 'ceita', 0
        db 'trago', 0
        db 'linha', 0
        db 'narco', 0
        db 'bulir', 0
        db 'calor', 0
        db 'piche', 0
        db 'jazer', 0
        db 'apear', 0
        db 'resto', 0
        db 'ardis', 0
        db 'culta', 0
        db 'folha', 0
        db 'manto', 0
        db 'misto', 0
        db 'peita', 0
        db 'matar', 0
        db 'neste', 0
        db 'cosmo', 0
        db 'redor', 0
        db 'monta', 0
        db 'folia', 0
        db 'seiva', 0
        db 'queda', 0
        db 'chaga', 0
        db 'banto', 0
        db 'mover', 0
        db 'bolso', 0
        db 'barro', 0
        db 'limpo', 0
        db 'campa', 0
        db 'gemer', 0
        db 'retro', 0
        db 'macho', 0
        db 'calvo', 0
        db 'porca', 0
        db 'findo', 0
        db 'axial', 0
        db 'venho', 0
        db 'punha', 0
        db 'louro', 0
        db 'logia', 0
        db 'canil', 0
        db 'justa', 0
        db 'lutar', 0
        db 'farol', 0
        db 'fazes', 0
        db 'sabor', 0
        db 'arroz', 0
        db 'mimar', 0
        db 'sofia', 0
        db 'rente', 0
        db 'enjoo', 0
        db 'chave', 0
        db 'bedel', 0
        db 'veloz', 0
        db 'salva', 0
        db 'lousa', 0
        db 'firma', 0
        db 'baixa', 0
        db 'torna', 0
        db 'coevo', 0
        db 'zumbi', 0
        db 'longo', 0
        db 'vazia', 0
        db 'pedro', 0
        db 'sigla', 0
        db 'solta', 0
        db 'ousar', 0
        db 'forro', 0
        db 'falsa', 0
        db 'fugiu', 0
        db 'reler', 0
        db 'gueto', 0
        db 'tumba', 0
        db 'farto', 0
        db 'sexto', 0
        db 'outra', 0
        db 'corar', 0
        db 'lucro', 0
        db 'urgir', 0
        db 'subir', 0
        db 'dados', 0
        db 'louca', 0
        db 'nariz', 0
        db 'valer', 0
        db 'penca', 0
        db 'mania', 0
        db 'custo', 0
        db 'repor', 0
        db 'sugar', 0
        db 'toque', 0
        db 'cardo', 0
        db 'cacto', 0
        db 'disso', 0
        db 'modal', 0
        db 'versa', 0
        db 'passe', 0
        db 'diabo', 0
        db 'corte', 0
        db 'sadio', 0
        db 'ultra', 0
        db 'lento', 0
        db 'xampu', 0
        db 'pagar', 0
        db 'bruxa', 0
        db 'quite', 0
        db 'samba', 0
        db 'staff', 0
        db 'sinta', 0
        db 'nesga', 0
        db 'usual', 0
        db 'ferir', 0
        db 'bugre', 0
        db 'ceifa', 0
        db 'mimos', 0
        db 'garra', 0
        db 'olhos', 0
        db 'viger', 0
        db 'quais', 0
        db 'refil', 0
        db 'abade', 0
        db 'pazes', 0
        db 'pluma', 0
        db 'trair', 0
        db 'pular', 0
        db 'grife', 0
        db 'digna', 0
        db 'anzol', 0
        db 'sigma', 0
        db 'mouro', 0
        db 'filme', 0
        db 'podre', 0
        db 'roubo', 0
        db 'skate', 0
        db 'raiar', 0
        db 'couve', 0
        db 'nisso', 0
        db 'cervo', 0
        db 'viaje', 0
        db 'pavio', 0
        db 'beber', 0
        db 'dobro', 0
        db 'veado', 0
        db 'notar', 0
        db 'males', 0
        db 'volto', 0
        db 'ibope', 0
        db 'posta', 0
        db 'tacho', 0
        db 'abono', 0
        db 'focar', 0
        db 'cisco', 0
        db 'dique', 0
        db 'verme', 0
        db 'mecha', 0
        db 'surra', 0
        db 'buril', 0
        db 'perca', 0
        db 'bossa', 0
        db 'burla', 0
        db 'barra', 0
        db 'cedro', 0
        db 'farei', 0
        db 'curto', 0
        db 'caibo', 0
        db 'milho', 0
        db 'atlas', 0
        db 'cinza', 0
        db 'hirto', 0
        db 'domar', 0
        db 'regem', 0
        db 'germe', 0
        db 'valho', 0
        db 'cobra', 0
        db 'ibero', 0
        db 'untar', 0
        db 'baita', 0
        db 'azedo', 0
        db 'magno', 0
        db 'ninfa', 0
        db 'caput', 0
        db 'souto', 0
        db 'tropa', 0
        db 'veraz', 0
        db 'farra', 0
        db 'mofar', 0
        db 'regar', 0
        db 'maria', 0
        db 'cento', 0
        db 'rouco', 0
        db 'ducto', 0
        db 'bahia', 0
        db 'muita', 0
        db 'errar', 0
        db 'idade', 0
        db 'poste', 0
        db 'penha', 0
        db 'taxar', 0
        db 'teria', 0
        db 'encha', 0
        db 'tensa', 0
        db 'furto', 0
        db 'causo', 0
        db 'brasa', 0
        db 'vindo', 0
        db 'vazar', 0
        db 'baila', 0
        db 'donde', 0
        db 'forra', 0
        db 'sobra', 0
        db 'Pedro', 0
        db 'chega', 0
        db 'feira', 0
        db 'basta', 0
        db 'leque', 0
        db 'zorra', 0
        db 'guizo', 0
        db 'clara', 0
        db 'latim', 0
        db 'infra', 0
        db 'gruta', 0
        db 'vagem', 0
        db 'pondo', 0
        db 'reaja', 0
        db 'nudez', 0
        db 'ampla', 0
        db 'fobia', 0
        db 'sanha', 0
        db 'banda', 0
        db 'brejo', 0
        db 'mento', 0
        db 'polpa', 0
        db 'lombo', 0
        db 'tropo', 0
        db 'fibra', 0
        db 'canal', 0
        db 'apuro', 0
        db 'junta', 0
        db 'exmo.', 0
        db 'anima', 0
        db 'mossa', 0
        db 'hiper', 0
        db 'sonda', 0
        db 'cariz', 0
        db 'tosse', 0
        db 'serra', 0
        db 'bicha', 0
        db 'primo', 0
        db 'bardo', 0
        db 'rolar', 0
        db 'carga', 0
        db 'poria', 0
        db 'lagoa', 0
        db 'delta', 0
        db 'aipim', 0
        db 'menor', 0
        db 'prelo', 0
        db 'droga', 0
        db 'boate', 0
        db 'mirim', 0
        db 'burgo', 0
        db 'banir', 0
        db 'lance', 0
        db 'farda', 0
        db 'pizza', 0
        db 'safra', 0
        db 'loira', 0
        db 'genra', 0
        db 'venda', 0
        db 'pinto', 0
        db 'cerco', 0
        db 'morto', 0
        db 'soror', 0
        db 'fecho', 0

num_words equ ($ - words) / 6